export const ActionsId = {
    SET_QUERY_TEXT: "SET_QUERY_TEXT",
    SET_WEB_URL: "SET_WEB_URL",
    SET_TRIM_DUPLICATES: "SET_TRIM_DUPLICATES",
    SET_ROW_LIMIT: "SET_ROW_LIMIT",
    SET_START: "SET_START",
    SET_SKIP: "SET_SKIP",
    SET_SELECT_FIELDS: "SET_SELECT_FIELDS",
    SET_REFINERS: "SET_REFINERS",
    SET_FILTER: "SET_FILTER",
    SET_SORT: "SET_SORT",
    SET_RESULT_SOURCE: "SET_RESULT_SOURCE",
    SET_FETCHING_DATA: "SET_FETCHING_DATA",
    SET_COLLAPSED: "SET_COLLAPSED",
    SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
    SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
    SET_MESSAGE_DATA: "SET_MESSAGE_DATA",
    SET_ERROR_MESSAGE_DATA: "SET_ERROR_MESSAGE_DATA"
};

export const constants = {
    COMPONENT_DIV_ID: "spSearchBaseDiv",
    EMPTY_STRING: "",
    MODAL_DIALOG_TITLE: "Search",
    MODAL_DIALOG_WIDTH: "1000px",
    PROPS_TO_IGNORE: ["ClassificationLastScan"],
};
