export const PropertyActionID  = {
    CREATE_PROPERTY: 'CREATE_PROPERTY',
    UPDATE_PROPERTY: 'UPDATE_PROPERTY',
    DELETE_PROPERTY: 'DELETE_PROPERTY',
    SET_ALL_PROPERTIES: 'SET_ALL_PROPERTIES'
}
export const WindowActionID  = {
    SET_FILTER_TEXT: 'SET_FILTER_TEXT',
    SET_WORKING_ON_IT: 'SET_WORKING_ON_IT',
    SET_MESSAGE_DATA: 'SET_MESSAGE_DATA',
    SET_USER_PERMISSIONS: 'SET_USER_PERMISSIONS'    
}

export enum ItemMode {
    EDIT,
    CREATE,
    VIEW  
}