export const SpSiteContentConstants = {
    ERROR_MESSAGE_GET_ALL_SITE_CONTENT: "An error occurred getting all site content.",
    ERROR_MESSAGE_REINDEX_LIST: "An error occurred sending the list reindex request.",
    ERROR_MESSAGE_RESOLVER_GETTING_LISTS: "Getting the lists and libraries",
    ERROR_MESSAGE_RESOLVER_SETTING_VISIBILITY: "Setting the Visibility of the list",
    ERROR_MESSAGE_RESOLVER_SETTING_ATTACHMENTS: "Setting the attachments",
    ERROR_MESSAGE_RESOLVER_SETTING_NO_CRAWL: "Setting no crawl",
    ERROR_MESSAGE_RESOLVER_DELETING_LIST: "Deleting the list",
    ERROR_MESSAGE_SET_LIST_ATTACHMENTS_ENABLE: "An error occurred setting the attachments.",
    ERROR_MESSAGE_SET_LIST_NO_CRAWL: "An error occurred setting list crawl.",
    ERROR_MESSAGE_SET_LIST_VISIBILITY: "An error occurred setting the list visibility.",
    changeEvent: "spSiteContentStorechange",
    getContentErrorMessage: "Failed to get web lists",
    itemImageHeight: 25,
    itemImageWidth: 25,
    noOpenInNewTab: "List and libraries links will open in the current tab.",
    openInNewTab: "List and libraries links will open in a new tab.",
    permissionsPageUrlClose: "%7D",
    permissionsPageUrlMiddle: "%7D,list&List=%7B",
    permissionsPageUrlOpen: "/_layouts/user.aspx?obj=%7B",
    selectFields: [
        "RootFolder",
        "Title",
        "Id",
        "Hidden",
        "ItemCount",
        "Created",
        "ImageUrl",
        "LastItemModifiedDate",
        "Description",
        "EffectiveBasePermissions",
        "ParentWebUrl",
        "DefaultNewFormUrl",
        "EnableAttachments",
        "BaseTemplate",
        "BaseType",
        "NoCrawl"
    ],
    settingsRelativeUrl: "/_layouts/listedit.aspx?List=",
    showingAllItemsMessage: "Showing all lists and libraries.",
    showingHiddenItemsMessage: "Showing only hidden lists and libraries."
};

export const ActionsId = {
    HANDLE_ASYNC_ERROR: "HANDLE_ASYNC_ERROR",
    SET_FAVOURITE: "SET_FAVOURITE",
    SET_MESSAGE_DATA: "SET_MESSAGE_DATA",
    SET_OPEN_IN_NEW_TAB: "SET_OPEN_IN_NEW_TAB",
    SET_SHOW_ALL: "SET_SHOW_ALL",
    SET_SITE_CONTENT: "SET_SITE_CONTENT",
    SET_SITE_CONTENT_AND_MESSAGE: "SET_SITE_CONTENT_AND_MESSAGE",
    SET_TEXT_FILTER: "SET_TEXT_FILTER",
    SET_WORKING_ON_IT: "SET_WORKING_ON_IT"
};
