export const ActionsId  = {
    SET_SITE_FEATURES: 'SET_SITE_FEATURES',
    SET_WEB_FEATURES: 'SET_WEB_FEATURES',
    ACTIVATE_FEATURE: 'ACTIVATE_FEATURE',
    DEACTIVATE_FEATURE: 'DEACTIVATE_FEATURE',
    SET_FILTER_TEXT: 'SET_FILTER_TEXT',
    SET_WORKING_ON_IT: 'SET_WORKING_ON_IT',
    SET_MESSAGE_DATA: 'SET_MESSAGE_DATA',
    SET_NO_PERMISSIONS: 'SET_NO_PERMISSIONS',
    SET_ALL_FEATURES: 'SET_ALL_FEATURES'
}


export const constants  = {
    COMPONENT_DIV_ID: 'spFeaturesBaseDiv',
    MODAL_DIALOG_TITLE: 'Site/Web Features',
    MODAL_DIALOG_WIDTH: '800px',
    EMPTY_STRING: '',
    MESSAGE_USER_NO_PERMISSIONS:'The current user does NOT have permissions to work with the web property bags.'
}
