/* tslint:disable:max-line-length */
export const constants  = {
    AXIOS_HEADER_ACCEPT: "application/json;odata=nometadata",
    BUTTON_TEX_CANCEL: "Cancel",
    BUTTON_TEX_OK: "Ok",
    HTML_ATTR_ID: "id",
    HTML_TAG_BODY: "body",
    HTML_TAG_DIV: "div",
    HTML_TAG_FORM: "form",
    HTML_TAG_HEAD: "head",
    HTML_TAG_INPUT: "input",
    HTML_TAG_LINK: "link",
    HTML_TAG_SCRIPT: "script",
    MESSAGE_CANT_CHECK_PERMISSIONS: "Cannot check permissions against a non-securable object.",
    MESSAGE_CHECKING_CURRENT_USER_PERMISSIONS: "Checking current's user permission",
    MESSAGE_GETTING_WEB_URL: "Getting Web URL",
    MODAL_WRAPPER_CLOSE_BUTTON_HREF: "javascript:void(0)",
    MODAL_WRAPPER_CLOSE_BUTTON_TEXT: "Close",
    SCRIPT_TAG_TYPE: "text/javascript",
    SP_TYPE_CLIENTCONTEXT: "SP.ClientContext",
    STYLE_TAG_ATTR_REL: "stylesheet",
    STYLE_TAG_ATTR_TYPE: "text/css",
    STYLE_TAG_ID: "spChromeDevToolStyles",
    SP_INFO_TAG_ID: "spChromeDevToolSpInfo",
    TYPE_OF_FUNCTION: "function",
    TYPE_OF_UNDEFINED: "undefined",
    TYPE_OF_STRING: "string",
    URL_LAYOUTS: "/_layouts/15/",
    URL_SLASH: "/",
    URL_SP: "sp.js",
    URL_SP_RUNTIME: "SP.Runtime.js",
    URL_INIT: "init.js",
    URL_SP_MS_AJAX: "MicrosoftAjax.js",
    GLOBAL_NAME_SP: "SP.Utilities",
    GLOBAL_NAME_SP_RUNTIME: "SP.SOD",
    GLOBAL_NAME_INIT: "$_global_init",
    GLOBAL_NAME_SP_MS_AJAX: "Sys",
    WORKING_ON_IT_TEXT: "Working on it...",
    GUID_REGEX: /^[0-9aA-fF]{8}-([0-9aA-fF]{4}-){3}[0-9aA-fF]{12}$/
};
/* tslint:enable:max-line-length */
